# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'rainyShainySunShine' do
 
  use_frameworks!

  # Pods for rainyShainySunShine
  pod 'Alamofire', '~> 4.5'

end
